root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
  - 'unicorn'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:unicorn/recommended'
env:
  node: true
  es2024: true
rules:
  unicorn/filename-case: off
  unicorn/no-null: off
